Enhanced Secret Functionality
FairwindsOps/reckoner pull request #271
Opened 2021-01-18 03:48 UTC by ejether

This PR adds a new key to the course and new functionality for secret handling. The `secret` top level key is a list of maps that define how and hwere to get a secret value. The secrets are merged into the `os.environ` and that is used as before. Duplicate variables are not allowed. 

This pr adds two providers `AWSParameterStore` and `ShellExecutor`

2021-01-18 03:52 UTC, ejether commented
I still need to add documentation and tests for the `ShellExecutor` but I wanted to get this out there sooner. 
I'd love feedback on the code structure, if there is any, before I start to go to town on the documentation. 
The way the secret provider frame is written feels like it might be wonky. with `SecretProvider.get_value()` not accepting arguments. 🤷 

All in all, this was really fun to write and it came together really nicely.

2021-01-18 03:53 UTC, ejether commented
Closes: https://github.com/FairwindsOps/reckoner/issues/268

2021-01-18 19:45 UTC, ejether commented
@pthomison you might be interested in this as well.

2021-01-19 18:04 UTC, ejether commented on end_to_end_testing/course_files/13_test_lint_bad_secret.yml
> +- name: testname
```suggestion
- name: testname

```

2021-01-19 18:04 UTC, ejether commented on end_to_end_testing/course_files/13_test_lint_good_secret.yml
> +  allowed: test_other_allowed
```suggestion
  allowed: test_other_allowed
  
```

2021-01-19 18:04 UTC, ejether commented on end_to_end_testing/tests/13_schema.yaml
> +    - result.systemout ShouldContainString 'No schema validation errors found'
```suggestion
    - result.systemout ShouldContainString 'No schema validation errors found'

```

2021-01-20 20:13 UTC, sudermanjr requested changes
Seems good. Haven't tested myself, but the code looks good. I didn't notice, is there an e2e test that uses the shell executor to test that code path?

2021-01-20 20:13 UTC, sudermanjr commented on reckoner/tests/test_course.py
> +        # Doing this because the way secretes get injected into the environment
```suggestion
        # Doing this because the way secrets get injected into the environment
```

2021-01-20 20:25 UTC, ejether commented on docs/README.md
> +
```suggestion
```

2021-01-20 20:28 UTC, ejether commented on reckoner/course.py
> +                raise ReckonerException(
Agreed, we will need some optimization if we add secrets at the chart and the global scope. 
This was the simplest and least disruptive way I could think of to accomplish the global scope.

2021-01-20 21:21 UTC, ejether commented
There is not an e2e test for that. I'll add one.

2021-01-21 15:58 UTC, sudermanjr approved these changes
I am happy with this as it is. The structure seems sufficient for MVP, and it will solve most use-cases. Waiting for review from Luke before I merge.

2021-01-27 15:30 UTC, lucasreed approved these changes

2021-02-01 18:20 UTC, merged